<?php

namespace ManagerMembers\Repositories;

use ManagerMembers\Presenters\PermissionPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use ManagerMembers\Repositories\PermissionRepository;
use ManagerMembers\Models\Permission;
use ManagerMembers\Validators\PermissionValidator;

/**
 * Class PermissionRepositoryEloquent.
 *
 * @package namespace ApiLimp\Repositories;
 */
class PermissionRepositoryEloquent extends BaseRepository implements PermissionRepository
{
    protected $skipPresenter = true;

    public function findWherePermission($name){
        return $this->model->where('name',$name)->first();
    }
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Permission::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function presenter()
    {
        return PermissionPresenter::class; // TODO: Change the autogenerated stub
    }

}
